/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

int *
add_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

    if(argp->op==0){
        printf("add (%d, %d) is called \n", argp->a,argp->b);
        result = argp->a + argp->b;
    }

    if(argp->op==1){
        printf("sub (%d, %d) is called \n", argp->a,argp->b);
        result = argp->a - argp->b;
    }

    if(argp->op==2){
        printf("multiply (%d, %d) is called \n", argp->a,argp->b);
        result = argp->a * argp->b;
    }

    if(argp->op==3){
        printf("divide (%d, %d) is called \n", argp->a,argp->b);
        result = argp->a / argp->b;
    }

	return &result;
}
