/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdlib.h>
#include "rand.h"

void *
inicializa_random_1_svc(long *argp, struct svc_req *rqstp)
{
	static char * resultado;
	srand48(*argp);
	return (void *) &resultado; // Aun que no regresa nada es importante generar el return ya que la funcion espera un retorno de void
}

double *
obtiene_nuevo_random_1_svc(void *argp, struct svc_req *rqstp)
{
	static double  resultado;
	resultado = drand48();
	return &resultado;
}
